import {createNewsService} from './server/news/rss.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {loadConfig} from './server/config.mjs';
const project=path.dirname(fileURLToPath(import.meta.url));process.chdir(project);const config=loadConfig();const root=path.join(project,process.env.SERVE_BUILD==='1'?'build':'dist');const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.ttf':'font/ttf','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'};
const newsService=createNewsService();
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' https://api.open-meteo.com https://geocoding-api.open-meteo.com; frame-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'");
 if(req.headers.host!==new URL(config.origin).host){res.writeHead(421);return res.end('Use '+config.origin+' to preserve your private session.')}
 try{const url=new URL(req.url,config.origin);if(url.pathname==='/api/news'){if(req.method!=='GET'){res.writeHead(405);return res.end()};const data=await newsService.get({force:url.searchParams.get('refresh')==='1',category:url.searchParams.get('category')||''});res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});return res.end(JSON.stringify(data))}if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/auth/')){res.writeHead(404);return res.end('Not found')}if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end()};const pathname=decodeURIComponent(url.pathname);if(pathname.split('/').some(x=>x.startsWith('.'))){res.writeHead(403);return res.end()};const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end()};fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end('Not found')};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:data)})}catch{res.writeHead(400);res.end('Invalid request')}
});server.listen(config.port,'127.0.0.1',()=>console.log(`double’s home private: ${config.origin}`));
function stop(){server.close(()=>process.exit(0))}process.on('SIGINT',stop);process.on('SIGTERM',stop);
