import {XMLParser,XMLValidator} from 'fast-xml-parser';
import {createHash} from 'node:crypto';
export const FEEDS=[
 {id:'rr-geral',source:'Renascença / RR',label:'RR Informação',url:'https://rr.pt/rss/rssfeed.aspx',category:''},
 {id:'rtp-latest',source:'RTP Notícias',label:'RTP Últimas',url:'https://www.rtp.pt/noticias/rss',category:''},
 {id:'rtp-economia',source:'RTP Notícias',label:'RTP Economia',url:'https://www.rtp.pt/noticias/rss/economia',category:'Economia'},
 {id:'rtp-pais',source:'RTP Notícias',label:'RTP País',url:'https://www.rtp.pt/noticias/rss/pais',category:'Sociedade'}
];
export const TTL=45*60*1000;
const parser=new XMLParser({ignoreAttributes:false,parseTagValue:false,parseAttributeValue:false,processEntities:true,htmlEntities:true,trimValues:true});
const value=x=>typeof x==='string'?x:typeof x==='number'?String(x):x?.['#text']||'';
const array=x=>x==null?[]:Array.isArray(x)?x:[x];
export function plain(x){return value(x).slice(0,80000).replace(/<\s*(script|style|iframe|figure|figcaption)\b[^>]*>[\s\S]*?<\/\s*\1\s*>/gi,' ').replace(/<\s*(?:br\s*\/?|\/p|\/div|\/li)\s*>/gi,'\n\n').replace(/<[^>]*>/g,' ').replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(_,k)=>{const names={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};if(names[k])return names[k];const n=k[1]?.toLowerCase()==='x'?parseInt(k.slice(2),16):Number(k.slice(1));return n>0&&n<=0x10ffff?String.fromCodePoint(n):''}).replace(/<[^>]*>/g,' ').replace(/[\t \r]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
export function articleURL(raw){try{const u=new URL(raw);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)return '';if(!['rr.pt','www.rr.pt','rr.sapo.pt','www.rtp.pt','rtp.pt'].includes(u.hostname))return '';u.protocol='https:';u.hash='';for(const key of [...u.searchParams.keys()])if(/^utm_|^fbclid$|^gclid$/i.test(key))u.searchParams.delete(key);return u.href}catch{return ''}}
export function classify(title,url,feedCategory=''){const slug=url.toLowerCase(),t=title.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();if(/\/(cultura|desporto|noticiario-antena1)\//.test(slug))return '';if(/\/politica\//.test(slug))return 'Política';if(/\/economia\//.test(slug)||feedCategory==='Economia')return 'Economia';if(/\b(parlamento|partido|eleico|eleicoes|presidente da republica|primeiro.ministro|assembleia da republica|deputados?|governo|ministro)\b/.test(t))return 'Política';if(feedCategory==='Sociedade'||/\/pais\//.test(slug)||/\b(escola|educacao|habitacao|saude|hospital|imigracao|imigrantes|trabalho|emprego|ambiente|professores|transportes|rendas|incendio|policia|universidade)\b/.test(t))return 'Sociedade';return ''}
export function parseFeed(xml,feed,now=Date.now()){if(xml.length>2_000_000||/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('Unsupported XML');if(XMLValidator.validate(xml)!==true)throw Error('Invalid RSS XML');const root=parser.parse(xml);const items=root.rss?.channel?.item||root.feed?.entry;if(!items)throw Error('RSS has no items');return array(items).slice(0,150).flatMap(item=>{const link=typeof item.link==='string'?item.link:array(item.link).find(l=>l['@_rel']==='alternate'||!l['@_rel'])?.['@_href'];const url=articleURL(link||value(item.guid));const title=plain(item.title).slice(0,400),date=Date.parse(value(item.pubDate||item.published||item.updated||item['dc:date']));if(!url||!title||!Number.isFinite(date)||date>now+300000)return [];const description=plain(item.description||item.summary);const content=plain(item['content:encoded']||item.content);const availableText=(content.length>description.length?content:description).slice(0,30000);const category=classify(title+' '+description,url,feed.category);if(!category)return [];return [{id:createHash('sha256').update(url).digest('hex').slice(0,24),title,source:feed.source,category,publishedAt:new Date(date).toISOString(),description:description.slice(0,2000),availableText,url,textKind:content.length>description.length?'RSS CONTENT':'RSS SUMMARY',feed:feed.label}];});}
async function readFeed(feed,fetcher){const response=await fetcher(feed.url,{redirect:'error',headers:{Accept:'application/rss+xml, application/atom+xml, text/xml','User-Agent':'double-home-private-rss-reader/1.0'},signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('HTTP '+response.status);const reader=response.body.getReader();let length=0;const chunks=[];try{for(;;){const {value,done}=await reader.read();if(done)break;length+=value.length;if(length>2_000_000)throw Error('RSS exceeds size limit');chunks.push(value)}}finally{await reader.cancel().catch(()=>{})}return new TextDecoder().decode(Buffer.concat(chunks));}
export function createNewsService({fetcher=fetch,clock=Date.now,feeds=FEEDS}={}){const cache=new Map();let inflight=null,lastAttempt=0;async function refresh(){await Promise.all(feeds.map(async feed=>{const old=cache.get(feed.id);try{const articles=parseFeed(await readFeed(feed,fetcher),feed,clock());cache.set(feed.id,{articles,updatedAt:clock(),status:'ok',error:''})}catch(error){cache.set(feed.id,{articles:old?.articles||[],updatedAt:old?.updatedAt||null,status:old?.articles?.length?'stale':'unavailable',error:error.message.startsWith('HTTP ')?error.message:'Feed temporarily unavailable'})}}));}
return {async get({force=false,category=''}={}){const now=clock();if(inflight)await inflight;else if(!lastAttempt||now-lastAttempt>=TTL||(force&&now-lastAttempt>=60000)){lastAttempt=now;inflight=refresh();try{await inflight}finally{inflight=null}}const seen=new Set(),titles=new Set();const articles=feeds.flatMap(f=>cache.get(f.id)?.articles||[]).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)).filter(a=>{if(Date.parse(a.publishedAt)<clock()-72*3600000||Date.parse(a.publishedAt)>clock()+300000)return false;const key=a.title.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');if(seen.has(a.url)||titles.has(key))return false;seen.add(a.url);titles.add(key);return !category||a.category===category});return {articles,sources:feeds.map(f=>({id:f.id,label:f.label,url:f.url,status:cache.get(f.id)?.status||'unavailable',updatedAt:cache.get(f.id)?.updatedAt||null,error:cache.get(f.id)?.error||''})),checkedAt:lastAttempt,cacheMinutes:45,refreshAfter:lastAttempt+TTL,cost:'free',mode:'live-rss'};}};}
